// data/glossary.js
// Each term may carry `aliases` — phrases that, when found in case prose, become
// hoverable links to this definition (see js/linkify.js).
export const GLOSSARY = {
  cm: { longName: { en: 'Committee of Ministers', pl: 'Komitet Ministrów' },
        aliases: ['Committee of Ministers', 'CM'],
        definition: { en: 'The Council of Europe body that supervises whether states carry out ECtHR judgments.',
                      pl: 'Organ Rady Europy nadzorujący wykonywanie wyroków ETPC przez państwa.' } },
  krs: { longName: { en: 'National Council of the Judiciary (KRS)', pl: 'Krajowa Rada Sądownictwa (KRS)' },
        aliases: ['National Council of the Judiciary', 'neo-KRS', 'KRS', 'NCJ'],
        definition: { en: 'The body that nominates every Polish judge. How it was politicised: a 2017 law cut short its sitting members’ terms and gave parliament (the Sejm) the power to elect its 15 judicial members — who used to be chosen by judges. That put judicial appointments under political control: the root defect behind most of these cases.',
                      pl: 'Organ wskazujący każdego polskiego sędziego. Jak go upolityczniono: ustawa z 2017 r. skróciła kadencje urzędujących członków i dała parlamentowi (Sejmowi) prawo wyboru jej 15 sędziowskich członków — wcześniej wybieranych przez sędziów. To poddało powołania sędziowskie kontroli politycznej: źródłowa wada większości tych spraw.' } },
  discChamber: { longName: { en: 'Disciplinary Chamber', pl: 'Izba Dyscyplinarna' },
        aliases: ['Disciplinary Chamber'],
        definition: { en: 'A chamber of the Supreme Court created in 2018 to discipline judges and lift their immunity, staffed with judges appointed through the politicised KRS. The EU and Strasbourg courts found it was not independent; it was abolished in 2022.',
                      pl: 'Izba Sądu Najwyższego utworzona w 2018 r. do dyscyplinowania sędziów i uchylania ich immunitetu, obsadzona sędziami powołanymi przez upolitycznioną KRS. Trybunały UE i ETPC uznały, że nie była niezależna; zlikwidowano ją w 2022 r.' },
        quote: { text: { en: 'the objective circumstances in which that court was formed, its characteristics and the means by which its members have been appointed are capable of giving rise to legitimate doubts … as to … imperviousness to external factors',
                         pl: 'obiektywne okoliczności utworzenia tego sądu, jego cechy oraz sposób powołania jego członków mogą wzbudzać uzasadnione wątpliwości … co do … niezależności od czynników zewnętrznych' },
                 source: 'CJEU, A.K. and Others (2019)' } },
  cerpa: { longName: { en: 'Chamber of Extraordinary Review and Public Affairs (CERPA)', pl: 'Izba Kontroli Nadzwyczajnej i Spraw Publicznych (IKNiSP)' },
        aliases: ['Chamber of Extraordinary Review and Public Affairs', 'Extraordinary Review Chamber', 'CERPA'],
        definition: { en: 'A new Supreme Court chamber that decides "extraordinary appeals" and election disputes. Its judges were appointed through the politicised KRS — in one case despite a court order freezing the appointment — so European courts found it was not a lawful tribunal.',
                      pl: 'Nowa izba Sądu Najwyższego rozpoznająca „skargi nadzwyczajne” i spory wyborcze. Jej sędziów powołano przez upolitycznioną KRS — w jednym przypadku mimo sądowego wstrzymania powołania — więc europejskie trybunały uznały, że nie była sądem zgodnym z prawem.' } },
  extraordinaryAppeal: { longName: { en: 'Extraordinary appeal', pl: 'Skarga nadzwyczajna' },
        aliases: ['extraordinary appeal'],
        definition: { en: 'A remedy created in 2017 that lets officials (e.g. the Prosecutor General) reopen final judgments years later — criticised as an "appeal in disguise" that undermines legal certainty.',
                      pl: 'Środek wprowadzony w 2017 r. pozwalający urzędnikom (np. Prokuratorowi Generalnemu) podważać prawomocne wyroki po latach — krytykowany jako „apelacja w przebraniu” godząca w pewność prawa.' } },
  muzzleLaw: { longName: { en: 'The "muzzle law"', pl: '„Ustawa kagańcowa”' },
        aliases: ['muzzle law'],
        definition: { en: 'A December 2019 law that barred judges from checking whether other judges were lawfully appointed and made doing so — or applying EU law on independence — a disciplinary offence. The CJEU held it broke EU law.',
                      pl: 'Ustawa z grudnia 2019 r., która zakazała sędziom badania, czy inni sędziowie zostali zgodnie z prawem powołani, i czyniła z tego — lub ze stosowania prawa UE o niezależności — przewinienie dyscyplinarne. TSUE uznał, że łamała prawo UE.' },
        quote: { text: { en: 'national rules which expose national judges to disciplinary proceedings as a result of … a reference … to the Court for a preliminary ruling cannot … be permitted',
                         pl: 'przepisy krajowe narażające sędziów krajowych na postępowania dyscyplinarne z powodu … skierowania pytania prejudycjalnego do Trybunału … nie mogą być dopuszczone' },
                 source: 'CJEU, Miasto Łowicz (2020)' } },
  enhanced: { longName: { en: 'Enhanced supervision', pl: 'Nadzór wzmocniony' },
        aliases: ['enhanced supervision'],
        definition: { en: 'A closer Committee of Ministers procedure for serious or systemic execution problems.',
                      pl: 'Zaostrzona procedura Komitetu Ministrów dla poważnych lub systemowych problemów z wykonaniem.' } },
  standard: { longName: { en: 'Standard supervision', pl: 'Nadzór standardowy' },
        aliases: ['standard supervision'],
        definition: { en: 'The default Committee of Ministers procedure for execution that raises no systemic concern.',
                      pl: 'Domyślna procedura Komitetu Ministrów dla wykonania niebudzącego problemów systemowych.' } },
  pilot: { longName: { en: 'Pilot judgment', pl: 'Wyrok pilotażowy' },
        aliases: ['pilot judgment'],
        definition: { en: 'An ECtHR judgment identifying a systemic problem behind many similar cases and indicating general remedies.',
                      pl: 'Wyrok ETPC wskazujący systemowy problem stojący za wieloma podobnymi sprawami i środki generalne.' } },
  art19teu: { longName: { en: 'Article 19(1) TEU', pl: 'Art. 19 ust. 1 TUE' },
        definition: { en: 'Requires EU states to provide remedies sufficient to ensure effective legal protection — read as guaranteeing independent courts.',
                      pl: 'Wymaga od państw UE środków zapewniających skuteczną ochronę prawną — odczytywany jako gwarancja niezależnych sądów.' } },
  art47charter: { longName: { en: 'Article 47 of the Charter', pl: 'Art. 47 Karty' },
        definition: { en: 'The EU Charter right to an effective remedy and a fair trial before an independent tribunal.',
                      pl: 'Prawo z Karty UE do skutecznego środka prawnego i rzetelnego procesu przed niezawisłym sądem.' } },
  art6echr: { longName: { en: 'Article 6 ECHR', pl: 'Art. 6 EKPC' },
        definition: { en: 'The Convention right to a fair hearing by an independent and impartial tribunal established by law.',
                      pl: 'Prawo z Konwencji do rzetelnego procesu przed niezawisłym sądem ustanowionym ustawą.' } },
  art8echr: { longName: { en: 'Article 8 ECHR', pl: 'Art. 8 EKPC' },
        definition: { en: 'The Convention right to respect for private and family life — which can include a person’s professional life and reputation.',
                      pl: 'Prawo z Konwencji do poszanowania życia prywatnego i rodzinnego — obejmujące także życie zawodowe i dobre imię.' } },
  art10echr: { longName: { en: 'Article 10 ECHR', pl: 'Art. 10 EKPC' },
        definition: { en: 'The Convention right to freedom of expression — which protects judges speaking out in defence of judicial independence.',
                      pl: 'Prawo z Konwencji do wolności wypowiedzi — chroniące także sędziów występujących w obronie niezależności sądownictwa.' } },
  art14echr: { longName: { en: 'Article 14 ECHR', pl: 'Art. 14 EKPC' },
        definition: { en: 'The Convention prohibition of discrimination in the enjoyment of the other Convention rights.',
                      pl: 'Zakaz dyskryminacji w korzystaniu z pozostałych praw konwencyjnych.' } },
  art18echr: { longName: { en: 'Article 18 ECHR', pl: 'Art. 18 EKPC' },
        definition: { en: 'Bars states from limiting Convention rights for any purpose other than those the Convention allows — used to expose ulterior, bad-faith motives.',
                      pl: 'Zakazuje ograniczania praw konwencyjnych w celach innych niż dozwolone — służy ujawnianiu ukrytych, nielojalnych motywów.' } },
};
